# super user permissions
language: generic
sudo: required
services:
    - docker 

before_install:
    - docker build -t krisedward/docker-react -f dockerfile.dev .

script:
    - docker run -e CI=true krisedward/docker-react npm run test